### ISSUE TITLE
Question Clarification 

### ISSUE THREAD

**Issue by hd371** [dataanalysis3/assignment-3#1]
With reference to the last question on assignment 3: "1. To simplify interpretation, keep only the respondents with non-missing values for political interest in all seven waves."

As well as removing NAs, does this also mean removing respondents' scores from the waves that they have participated if they have not provided a political interest score for all 7 waves? i.e. A male who has participated in waves 1,2,3,5,6,7,but not wave 4. Do we remove just the wave 4 data? or also his other responses on the other waves? 

Many thanks

**Comment by abessudnov** [comment]
If response is missing in any of the waves all data for this individual should be removed.
